// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_500.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/api/career.tsx";
import * as $4 from "./routes/api/signOut.tsx";
import * as $5 from "./routes/career.tsx";
import * as $6 from "./routes/edit.tsx";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/profile.tsx";
import * as $9 from "./routes/signIn.tsx";
import * as $$0 from "./islands/Icon.tsx";
import * as $$1 from "./islands/Navbar.tsx";
import * as $$2 from "./islands/careers.tsx";
import * as $$3 from "./islands/replace.tsx";
import * as $$4 from "./islands/userBaseInfo.tsx";

const manifest = {
  routes: {
    "./routes/_500.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/api/career.tsx": $3,
    "./routes/api/signOut.tsx": $4,
    "./routes/career.tsx": $5,
    "./routes/edit.tsx": $6,
    "./routes/index.tsx": $7,
    "./routes/profile.tsx": $8,
    "./routes/signIn.tsx": $9,
  },
  islands: {
    "./islands/Icon.tsx": $$0,
    "./islands/Navbar.tsx": $$1,
    "./islands/careers.tsx": $$2,
    "./islands/replace.tsx": $$3,
    "./islands/userBaseInfo.tsx": $$4,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
